[project]
name = "wk6-mnist3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.8.0",
    "torchsummary>=1.5.1",
    "torchvision>=0.23.0",
    "matplotlib>=3.9.0",
    "tqdm>=4.67.1",
]
